# Generated by Django 4.0.6 on 2022-07-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('REGULAR', "Regular - Can't delete members"), ('ADMIN', 'Admin - Can delete members')], default='REGULAR', max_length=10),
        ),
    ]
