# Generated by Django 4.0.6 on 2022-07-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
    ]
